# Generated by Django 6.0.3 on 2026-03-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('TENTATIVE', 'Wstępna'), ('GUARANTEED', 'Gwarantowana'), ('CANCELLED', 'Anulowana'), ('CHECKED_IN', 'Zameldowano'), ('CHECKED_OUT', 'Wymeldowano')], default='GUARANTEED', max_length=20),
        ),
    ]
